# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16NmGMWf_6p3Ep4GT7Q5SPCNKuemur5YC
"""

import numpy as np
import matplotlib.pyplot as plt

x = np.linspace(0, 10, 100)
y = np.sin(x)

plt.plot(x, y, label='Sinus(x)', color='blue')


plt.title('Sinus Funksiyasining Grafiki')
plt.xlabel('X qiymatlari')
plt.ylabel('Y qiymatlari')

plt.grid(True)
plt.legend()

plt.show()

import numpy as np
import matplotlib.pyplot as plt
np.random.seed(0)
x = np.random.uniform(0, 10, 50)
y = np.random.uniform(0, 10, 50)
plt.scatter(x, y, color='blue', label='Nuqtalar')
plt.title('Tasodifiy Nuqtalar Scatter Grafiki')
plt.xlabel('X qiymatlari')
plt.ylabel('Y qiymatlari')
plt.grid(True)
plt.legend()
plt.show()

import pandas as pd
url = "https://raw.githubusercontent.com/Zulayho06/Maxsus-topshiriq/main/WHO%20COVID-19%20cases.csv"
data = pd.read_csv(url)
print("Ma'lumotlarning birinchi 5 qatori:")
print(data.head())
print("\nDataFrame haqida umumiy ma'lumot:")
print(data.info())
print("\nStatistik ma'lumotlar:")
print(data.describe())

uzbekistan_data = data[data['Country'] == 'Uzbekistan']
print("\nUzbekistan bo'yicha ma'lumotlar:")
print(uzbekistan_data.head())

filtered_data = data[data['Date_reported'] >= '2022-01-01']

print("\n2022-yil 1-yanvardan keyingi ma'lumotlar:")
print(filtered_data.head())

top_countries = data.groupby('Country')['New_cases'].sum().sort_values(ascending=False).head(10)
print("\nEng ko'p yangi kasallanish holatlari (Top 10):")
print(top_countries)

import matplotlib.pyplot as plt
top_countries.plot(kind='bar', color='orange')
plt.title('COVID-19 Yangi Kasallanishlar (Top 10 Davlat)')
plt.ylabel('Yangi Kasallanishlar')
plt.xlabel('Davlatlar')
plt.show()

pip install pillow

from google.colab.patches import cv2_imshow
import cv2
rasm1=cv2.imread("rasm1.jpg")
cv2_imshow(rasm1)
rasm=cv2.imread("rasm.jpg")
cv2_imshow(rasm)
rasm2=cv2.imread("rasm2.jpg")
cv2_imshow(rasm2)


oqqora=cv2.cvtColor(rasm,cv2.COLOR_BGR2GRAY)
cv2_imshow(oqqora)
oqqora=cv2.cvtColor(rasm1,cv2.COLOR_BGR2GRAY)
cv2_imshow(oqqora)
oqqora=cv2.cvtColor(rasm2,cv2.COLOR_BGR2GRAY)
cv2_imshow(oqqora)